experiment_name: "breastCancer_mb"
experiment_config:
  batch_size: 64
  size_test_set: 0
  use_own_batch_per_sample: True

gmmvi_runnner:
  log_metrics_interval: 5

temperature: 1.
start_seed: 10000


use_diagonal_covars: False
use_sample_database: True

