---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
account: "project01883"
partition: "ignored"
job-name: "sepyrux"    # this will be the experiment's name in slurm


# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 6
time: 0-06:00:00

path_to_template: "clusterwork_slurm.sbatch"

---
name: "DEFAULT"

# Required: Can also be set in DEFAULT
path: "/work/scratch/j_arenz/tmlr_evals/exp1/bc/sepyrux"   # location to save results in
iterations: 100000
repetitions: 10 # number of times one set of parameters is run
reps_per_job: 1
reps_in_parallel: 1 # need to be 1 in order for wandb to work properly

algorithm_id: "SEPYRUX"

params: {}

wandb:
    project: gmmvi-evals

---
name: "WINE"

experiment_id: "wine"

params:
  model_initialization:
    num_initial_components: 5

  ng_estimator_config:
    use_self_normalized_importance_weights: True

  weight_stepsize_adapter_config:
    initial_stepsize: 0.

  sample_selector_config:
    desired_samples_per_component: 945
    ratio_reused_samples_to_desired: 2.866834991644419

  component_stepsize_adapter_config:
    initial_stepsize: 4.111689418270218e-7
    min_stepsize: 5.561278794329045e-7
    max_stepsize: 0.149847750988142

  start_seed: 0

wandb:
  group: "sepyrux_eval"
---
name: "BC"

experiment_id: "breast_cancer"

params:
  model_initialization:
    num_initial_components: 5

  ng_estimator_config:
    use_self_normalized_importance_weights: True

  weight_stepsize_adapter_config:
    initial_stepsize: 0.

  sample_selector_config:
    desired_samples_per_component: 993
    ratio_reused_samples_to_desired: 2.556760661729829

  component_stepsize_adapter_config:
    initial_stepsize: 9.383857457678536e-07
    min_stepsize: 0.0006893427354680969
    max_stepsize: 0.1377884604526246

  mmd_evaluation_config:
    alpha: 20.
    sample_dir: "experiments/target_distributions/tests/breastcancer_gt_10k.npy"

  start_seed: 0

wandb:
  group: "sepyrux_eval"
---
name: "BCMB"

experiment_id: "breast_cancer_mb"

params:
  model_initialization:
    num_initial_components: 5

  ng_estimator_config:
    use_self_normalized_importance_weights: True

  weight_stepsize_adapter_config:
    initial_stepsize: 0.

  sample_selector_config:
    desired_samples_per_component: 837
    ratio_reused_samples_to_desired: 1.6785113812666568

  component_stepsize_adapter_config:
    initial_stepsize: 1.4664686140972583e-05
    min_stepsize: 9.559559340317592e-05
    max_stepsize: 0.35281378938073

  mmd_evaluation_config:
    alpha: 20.
    sample_dir: "experiments/target_distributions/tests/breastcancer_gt_10k.npy"

  start_seed: 0

wandb:
  group: "sepyrux_eval"

