component_stepsize_adapter_config:
  desc: null
  value:
    initial_stepsize: 0.001
gmmvi_runner_config:
  desc: null
  value:
    log_metrics_interval: 10
model_initialization:
  desc: null
  value:
    num_initial_components: 20
ng_estimator_config:
  desc: null
  value:
    use_self_normalized_importance_weights: true
sample_selector_config:
  desc: null
  value:
    desired_samples_per_component: 200
    ratio_reused_samples_to_desired: 0
use_sample_database:
  desc: null
  value: false
weight_stepsize_adapter_config:
  desc: null
  value:
    initial_stepsize: 0
