---
name: "GMM100"

experiment_id: "gmm100"

params:
  component_stepsize_adapter_config:
      initial_stepsize: 0.0001

  sample_selector_config:
      desired_samples_per_component: 300
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 10

  max_database_size: 2000000
wandb:
    group: "sepyfux_gmm100"