---
name: "GMM20"

experiment_id: "gmm20"

params:
  component_stepsize_adapter_config:
      initial_stepsize: 0.0005
      min_stepsize: 0.005
      max_stepsize: 0.5

  sample_selector_config:
      desired_samples_per_component: 200
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 25

wandb:
    group: "sepyrux_gmm20"