---
name: "GMM20"

experiment_id: "gmm20"

params:
  component_stepsize_adapter_config:
      initial_stepsize: 0.0001

  sample_selector_config:
      desired_samples_per_component: 100
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 10

wandb:
    group: "sepyfux_gmm20"
---