
---
name: "GC_mb"

experiment_id: "german_credit_mb"

params:
    model_initialization:
        num_initial_components: 5

    sample_selector_config:
      desired_samples_per_component: 700
      ratio_reused_samples_to_desired: 0.

    weight_stepsize_adapter_config:
        initial_stepsize: 0.005

    component_stepsize_adapter_config:
        initial_stepsize: 0.0001

wandb:
    group: "sepyfux_gcmb"
---