---
name: "Planar4"

experiment_id: "planar_robot_4"

params:
    component_stepsize_adapter_config:
        initial_stepsize: 0.0005
        min_stepsize: 0.005
        max_stepsize: 0.1

    sample_selector_config:
        desired_samples_per_component:  150
        ratio_reused_samples_to_desired: 0.

    weight_stepsize_adapter_config:
        initial_stepsize: 0.85

    model_initialization:
      num_initial_components: 100
wandb:
    group: "sepyrux_planar_4"
---