---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
account: "project01883"
partition: "ignored"
job-name: "septrux"    # this will be the experiment's name in slurm


# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 6
time: 1-00:00:00

path_to_template: "cluster/experiments/clusterwork_slurm.sbatch"

---
name: "DEFAULT"

# Required: Can also be set in DEFAULT
path: "/work/scratch/j_arenz/tmlr_evals/exp1/bc/septrux"   # location to save results in
iterations: 100000
repetitions: 10 # number of times one set of parameters is run
reps_per_job: 1
reps_in_parallel: 1 # need to be 1 in order for wandb to work properly

algorithm_id: "SEPTRUX"

params: {}

wandb:
    project: gmmvi-evals

---
name: "WINE"

experiment_id: "wine"

params:
  model_initialization:
    num_initial_components: 5

  ng_estimator_config:
    use_self_normalized_importance_weights: True

  weight_stepsize_adapter_config:
    initial_stepsize: 0.

  sample_selector_config:
    desired_samples_per_component: 908
    ratio_reused_samples_to_desired: 1.188723817139543

  component_stepsize_adapter_config:
    initial_stepsize: 0.5594459382619501
    min_stepsize: 0.001539518122867161
    max_stepsize: 0.643232598116139

  start_seed: 0

wandb:
  group: "septrux_eval"
---
