---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
account: "project01883"
partition: "ignored"
job-name: "stkr"    # this will be the experiment's name in slurm

# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 3
time: 2-00:00:00

path_to_template: "clusterwork_slurm.sbatch"

---
name: "DEFAULT"

# Required: Can also be set in DEFAULT
path: "/work/scratch/j_arenz/exp3_eval/samtron/"   # location to save results in
iterations: 1000000
repetitions: 10 # number of times one set of parameters is run
reps_per_job: 1
reps_in_parallel: 1 # need to be 1 in order for wandb to work properly

algorithm_id: "SAMTRON"

params:
    model_initialization:
        num_initial_components: 1

    num_component_adapter_config:
        del_iters: 100
        add_iters: 30
        num_prior_samples: 0

    sample_selector_config:
        desired_samples_per_component: 100
        ratio_reused_samples_to_desired: 1.61803

    component_stepsize_adapter_config:
        initial_stepsize: 0.1
        min_stepsize: 0.001
        max_stepsize: 1.

    weight_stepsize_adapter_config:
        initial_stepsize: 0.1
        min_stepsize: 0.00001
        max_stepsize: 4.

wandb:
    project: gmmvi-exp3-eval

---
name: "BC"

experiment_id: "breast_cancer"

params:
    num_component_adapter_config:
      del_iters: 100
      add_iters: 25

    sample_selector_config:
      desired_samples_per_component: 250
      ratio_reused_samples_to_desired: 0.

    component_stepsize_adapter_config:
      initial_stepsize: 0.01

wandb:
    group: "samtron_bc"
---
name: "GC"

experiment_id: "german_credit"

params:
    num_component_adapter_config:
      del_iters: 100
      add_iters: 25

    sample_selector_config:
      desired_samples_per_component: 400
      ratio_reused_samples_to_desired: 1.61803

    component_stepsize_adapter_config:
      initial_stepsize: 0.2

wandb:
    group: "samtron_gc"
---
name: "BC_mb"

experiment_id: "breast_cancer_mb"

params:
    num_component_adapter_config:
      del_iters: 200
      add_iters: 250

    sample_selector_config:
      desired_samples_per_component: 100
      ratio_reused_samples_to_desired: 0.

    component_stepsize_adapter_config:
      initial_stepsize: 0.1

wandb:
    group: "samtron_bcmb2"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

params:
  component_stepsize_adapter_config:
    initial_stepsize: 0.05
    min_stepsize: 0.00005
    max_stepsize: 0.05

  sample_selector_config:
    desired_samples_per_component: 700
    ratio_reused_samples_to_desired: 0.

  num_component_adapter_config:
    del_iters: 200
    add_iters: 250

  weight_stepsize_adapter_config:
      initial_stepsize: 0.01
wandb:
    group: "samtron_gcmb"
---
name: "Planar4"

experiment_id: "planar_robot_4"

params:
  num_component_adapter_config:
    del_iters: 10
    add_iters: 1

  sample_selector_config:
      desired_samples_per_component: 100
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 5.

  model_initialization:
    num_initial_components: 100

  gmmvi_runner_config:
    log_metrics_interval: 125

  max_database_size: 2000000

wandb:
    group: "samtron_planar_4"
---
name: "GMM20"

experiment_id: "gmm20"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 30

  sample_selector_config:
      desired_samples_per_component: 300
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 0.1

  model_initialization:
    num_initial_components: 5

wandb:
    group: "samtron_gmm20"
---
name: "GMM100"

experiment_id: "gmm100"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 60

  sample_selector_config:
      desired_samples_per_component: 300
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 1

  max_database_size: 2000000

wandb:
    group: "samtron_gmm100"
---
name: "STM20"

experiment_id: "stm20"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 60

  component_stepsize_adapter_config:
    initial_stepsize: 0.1
    min_stepsize: 0.001
    max_stepsize: 1.

  sample_selector_config:
      desired_samples_per_component: 200
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 45

  max_database_size: 2000000

  gmmvi_runner_config:
      log_metrics_interval: 50
wandb:
    group: "samtron_stm20"
---
name: "STM300"

experiment_id: "stm300"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 200
    max_components: 150
    num_prior_samples: 1000

  component_stepsize_adapter_config:
    initial_stepsize: 0.1
    min_stepsize: 0.001
    max_stepsize: 1.

  sample_selector_config:
      desired_samples_per_component: 100
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 20

  gmmvi_runner_config:
      log_metrics_interval: 500
wandb:
    group: "samtron_stm300"
---
name: "WINE"

experiment_id: "wine"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 20
    max_components: 150
    num_prior_samples: 1000

  component_stepsize_adapter_config:
    initial_stepsize: 0.1
    min_stepsize: 0.001
    max_stepsize: 1.

  sample_selector_config:
      desired_samples_per_component: 750
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 1

  gmmvi_runner_config:
      log_metrics_interval: 100

  use_sample_database: False
  ng_estimator_config:
    only_use_own_samples: True
wandb:
    group: "samtron_WINE"
---
name: "TALOS"

experiment_id: "talos"

params:
  num_component_adapter_config:
    del_iters: 30
    add_iters: 100
    max_components: 250
    num_prior_samples: 1000

  sample_selector_config:
      desired_samples_per_component: 200
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 200

  gmmvi_runner_config:
      log_metrics_interval: 500
wandb:
    group: "samtron_talos"