---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
account: "project01883"
partition: "ignored"
job-name: "stkr"    # this will be the experiment's name in slurm

# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 3
time: 2-00:00:00

path_to_template: "clusterwork_slurm.sbatch"

---
name: "DEFAULT"

# Required: Can also be set in DEFAULT
path: "/work/scratch/j_arenz/exp3_eval/samyrux/"   # location to save results in
iterations: 1000000
repetitions: 10 # number of times one set of parameters is run
reps_per_job: 1
reps_in_parallel: 1 # need to be 1 in order for wandb to work properly

algorithm_id: "SAMYRUX"

params:
    model_initialization:
        num_initial_components: 1

    num_component_adapter_config:
        del_iters: 100
        add_iters: 30
        num_prior_samples: 0

    sample_selector_config:
        desired_samples_per_component: 600
        ratio_reused_samples_to_desired: 1.61803

    component_stepsize_adapter_config:
        initial_stepsize: 0.0005
        min_stepsize: 0.0005
        max_stepsize: 0.1

    weight_stepsize_adapter_config:
        initial_stepsize: 1.

wandb:
    project: gmmvi-exp3-eval

---
name: "BC"

experiment_id: "breast_cancer"

params:
    num_component_adapter_config:
      del_iters: 100
      add_iters: 25

    sample_selector_config:
      desired_samples_per_component: 500
      ratio_reused_samples_to_desired: 2.5

    component_stepsize_adapter_config:
        min_stepsize: 0.0005

wandb:
    group: "samyrux_bc"
---
name: "GC"

experiment_id: "german_credit"

params:
    num_component_adapter_config:
      del_iters: 100
      add_iters: 25

    sample_selector_config:
      desired_samples_per_component: 500
      ratio_reused_samples_to_desired: 1.61803

    component_stepsize_adapter_config:
        min_stepsize: 0.0001

wandb:
    group: "samyrux_gc"
---
name: "BC_mb"

experiment_id: "breast_cancer_mb"

params:
    num_component_adapter_config:
      del_iters: 200
      add_iters: 250

    sample_selector_config:
      desired_samples_per_component: 900
      ratio_reused_samples_to_desired: 1.61803

    weight_stepsize_adapter_config:
        initial_stepsize: 0.1

    component_stepsize_adapter_config:
      initial_stepsize: 0.00001

wandb:
    group: "samyrux_bcmb2"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

params:
  component_stepsize_adapter_config:
    initial_stepsize: 0.0001
    min_stepsize: 0.001
    max_stepsize: 0.1

  sample_selector_config:
    desired_samples_per_component: 700
    ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 0.005

  num_component_adapter_config:
    del_iters: 200
    add_iters: 250

wandb:
    group: "samyrux_gcmb"
---
name: "Planar4"

experiment_id: "planar_robot_4"

params:
  component_stepsize_adapter_config:
    initial_stepsize: 0.0001
    min_stepsize: 0.001
    max_stepsize: 0.1

  num_component_adapter_config:
    del_iters: 25
    add_iters: 25

  sample_selector_config:
      desired_samples_per_component: 300
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 0.85

  model_initialization:
    num_initial_components: 300

  gmmvi_runner_config:
    log_metrics_interval: 175

  max_database_size: 2000000
wandb:
    group: "samyrux_planar_4"
---
name: "GMM20"

experiment_id: "gmm20"

params:
  num_component_adapter_config:
    del_iters: 25
    add_iters: 25

  component_stepsize_adapter_config:
      initial_stepsize: 0.0001
      min_stepsize: 0.001
      max_stepsize: 0.1

  sample_selector_config:
      desired_samples_per_component: 100
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 5

wandb:
    group: "samyrux_gmm20"
---
name: "GMM100"

experiment_id: "gmm100"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 30

  component_stepsize_adapter_config:
      initial_stepsize: 0.0005
      min_stepsize: 0.005
      max_stepsize: 0.5

  sample_selector_config:
      desired_samples_per_component: 200
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 1.

  model_initialization:
    num_initial_components: 1

  max_database_size: 2000000
wandb:
    group: "samyrux_gmm100"
---
name: "STM20"

experiment_id: "stm20"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 30

  component_stepsize_adapter_config:
    initial_stepsize: 0.0005
    min_stepsize: 0.005
    max_stepsize: 0.5

  sample_selector_config:
      desired_samples_per_component: 100
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 0.8

  model_initialization:
    num_initial_components: 1

  max_database_size: 2000000

  gmmvi_runner_config:
      log_metrics_interval: 100
wandb:
    group: "samyrux_stm20"
---
name: "STM300"

experiment_id: "stm300"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 200
    max_components: 150
    num_prior_samples: 1000

  component_stepsize_adapter_config:
      initial_stepsize: 0.0005
      min_stepsize: 0.005
      max_stepsize: 0.5

  sample_selector_config:
      desired_samples_per_component: 200
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 0.8

  model_initialization:
    num_initial_components: 20

  gmmvi_runner_config:
      log_metrics_interval: 1000
wandb:
    group: "samyrux_stm300"
---
name: "WINE"

experiment_id: "wine"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 20
    max_components: 150
    num_prior_samples: 1000

  component_stepsize_adapter_config:
    initial_stepsize: 0.0001
    min_stepsize: 0.001
    max_stepsize: 0.1

  sample_selector_config:
      desired_samples_per_component: 1500
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 0.8

  model_initialization:
    num_initial_components: 20

  gmmvi_runner_config:
      log_metrics_interval: 200

  use_sample_database: False
  ng_estimator_config:
    only_use_own_samples: True
wandb:
    group: "samyrux_WINE"
---
name: "TALOS"

experiment_id: "talos"

params:
  num_component_adapter_config:
    del_iters: 100
    add_iters: 250
    max_components: 250
    num_prior_samples: 1000

  component_stepsize_adapter_config:
    initial_stepsize: 0.0005
    min_stepsize: 0.005
    max_stepsize: 0.5

  sample_selector_config:
      desired_samples_per_component: 500
      ratio_reused_samples_to_desired: 0.

  weight_stepsize_adapter_config:
      initial_stepsize: 0.8

  model_initialization:
    num_initial_components: 200

  gmmvi_runner_config:
      log_metrics_interval: 1000
wandb:
    group: "samyrux_talos"