---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
account: "project01800"
partition: "ignored"
job-name: "stkr"    # this will be the experiment's name in slurm

# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 3
time: 2-00:00:00

path_to_template: "clusterwork_slurm.sbatch"

---
name: "DEFAULT"

# Required: Can also be set in DEFAULT
path: "/work/scratch/j_arenz/exp3_hyperopt/samyrox/"   # location to save results in
iterations: 100000
repetitions: 1 # number of times one set of parameters is run
reps_per_job: 1
reps_in_parallel: 1 # need to be 1 in order for wandb to work properly

algorithm_id: "SAMYROX"

params:
    model_initialization:
        num_initial_components: 1

    num_component_adapter_config:
        del_iters: 100
        add_iters: 30
        num_prior_samples: 0

    sample_selector_config:
        desired_samples_per_component: 600
        ratio_reused_samples_to_desired: 1.61803

    component_stepsize_adapter_config:
        initial_stepsize: 0.0005
        min_stepsize: 0.0005
        max_stepsize: 0.1

    weight_stepsize_adapter_config:
        initial_stepsize: 0.2

wandb:
    project: gmmvi-exp3

---
name: "BC"

experiment_id: "breast_cancer"

list:
    num_component_adapter_config:
      del_iters: [100, 100]
      add_iters: [25, 50]

grid:
    sample_selector_config:
      desired_samples_per_component: [250, 500, 700]
      ratio_reused_samples_to_desired: [1.61803, 2.5]

    component_stepsize_adapter_config:
        min_stepsize: [0.0005, 0.00005]

wandb:
    group: "samyrox_bc"
---
name: "GC"

experiment_id: "german_credit"

list:
    num_component_adapter_config:
      del_iters: [100, 100]
      add_iters: [25, 50]

grid:
    sample_selector_config:
      desired_samples_per_component: [100, 250, 500]
      ratio_reused_samples_to_desired: [1.61803, 2.5]

    component_stepsize_adapter_config:
        min_stepsize: [0.001, 0.0001]

wandb:
    group: "samyrox_gc"
---
name: "BC_mb"

experiment_id: "breast_cancer_mb"

list:
    num_component_adapter_config:
      del_iters: [200, 200]
      add_iters: [250, 500]

grid:
    sample_selector_config:
      desired_samples_per_component: [500, 700, 900]
      ratio_reused_samples_to_desired: [1.61803]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.1, 0.01]

    component_stepsize_adapter_config:
      initial_stepsize: [0.0001, 0.00001]

wandb:
    group: "samyrox_bcmb"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

list:
  component_stepsize_adapter_config:
    initial_stepsize: [ 0.0001, 0.00005, 0.00001, 0.000005 ]
    min_stepsize: [ 0.001, 0.0005, 0.0001, 0.00005 ]
    max_stepsize: [ 0.1, 0.05, 0.01, 0.005 ]

grid:
    sample_selector_config:
      desired_samples_per_component: [700, 900, 1200]
      ratio_reused_samples_to_desired: [0.]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.1, 0.01]

    num_component_adapter_config:
      del_iters: [200]
      add_iters: [250]

wandb:
    group: "samyrox_gcmb"
---
name: "Planar4"

experiment_id: "planar_robot_4"

list:
  component_stepsize_adapter_config:
    initial_stepsize: [ 0.0001, 0.0001, 0.00005, 0.00005 ]
    min_stepsize: [ 0.001, 0.001, 0.0005, 0.0005 ]
    max_stepsize: [ 0.1, 0.1, 0.05, 0.05 ]

  num_component_adapter_config:
    del_iters: [ 10, 25, 10, 25 ]
    add_iters: [ 1, 25, 1, 25 ]

grid:
  sample_selector_config:
      desired_samples_per_component: [100, 200, 300]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 1., 0.1 ]

  model_initialization:
    num_initial_components: [100, 300]

  gmmvi_runner_config:
    log_metrics_interval: [ 175 ]

  max_database_size: [ 2000000 ]
wandb:
    group: "samyrox_planar_4"
---
name: "GMM20"

experiment_id: "gmm20"

list:
  num_component_adapter_config:
    del_iters: [ 25, 100, 25, 100 ]
    add_iters: [ 25, 30, 25, 30 ]

  component_stepsize_adapter_config:
      initial_stepsize: [0.0001, 0.0001, 0.0005, 0.0005]
      min_stepsize: [0.001, 0.001, 0.005, 0.005]
      max_stepsize: [0.1, 0.1, 0.5, 0.5]
grid:
  sample_selector_config:
      desired_samples_per_component: [100, 200, 300]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 1. ]

  model_initialization:
    num_initial_components: [1, 5]

wandb:
    group: "samyrox_gmm20"
---
name: "GMM100"

experiment_id: "gmm100"

list:
  num_component_adapter_config:
    del_iters: [ 100, 100, 100, 100 ]
    add_iters: [ 30, 60, 30, 60 ]

  component_stepsize_adapter_config:
      initial_stepsize: [0.0001, 0.0001, 0.0005, 0.0005]
      min_stepsize: [0.001, 0.001, 0.005, 0.005]
      max_stepsize: [0.1, 0.1, 0.5, 0.5]
grid:
  sample_selector_config:
      desired_samples_per_component: [100, 200, 300]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 1. ]

  model_initialization:
    num_initial_components: [1, 5]

  max_database_size: [2000000]
wandb:
    group: "samyrox_gmm100"
---
name: "STM20"

experiment_id: "stm20"

list:
  num_component_adapter_config:
    del_iters: [ 100, 100, 100, 100 ]
    add_iters: [ 30, 60, 30, 60 ]

  component_stepsize_adapter_config:
    initial_stepsize: [0.0001, 0.0001, 0.0005, 0.0005]
    min_stepsize: [0.001, 0.001, 0.005, 0.005]
    max_stepsize: [0.1, 0.1, 0.5, 0.5]

grid:
  sample_selector_config:
      desired_samples_per_component: [100, 200, 300]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 0.1 ]

  model_initialization:
    num_initial_components: [1, 5]

  max_database_size: [2000000]

  gmmvi_runner_config:
      log_metrics_interval: [100]
wandb:
    group: "samyrox_stm20"
---
name: "STM300"

experiment_id: "stm300"

list:
  num_component_adapter_config:
    del_iters: [ 100, 100, 100, 100 ]
    add_iters: [ 100, 200, 100, 200 ]
    max_components: [ 150, 150, 150, 150 ]
    num_prior_samples: [ 1000, 1000, 1000, 1000 ]

  component_stepsize_adapter_config:
      initial_stepsize: [0.0001, 0.0001, 0.0005, 0.0005]
      min_stepsize: [0.001, 0.001, 0.005, 0.005]
      max_stepsize: [0.1, 0.1, 0.5, 0.5]

grid:
  sample_selector_config:
      desired_samples_per_component: [100, 200]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 0.1 ]

  model_initialization:
    num_initial_components: [20, 30, 40]

  gmmvi_runner_config:
      log_metrics_interval: [1000]
wandb:
    group: "samyrox_stm300"
---
name: "WINE"

experiment_id: "wine"

list:
  num_component_adapter_config:
    del_iters: [ 100, 100, 100, 100 ]
    add_iters: [ 10, 20, 10, 20 ]
    max_components: [ 150, 150, 150, 150 ]
    num_prior_samples: [ 1000, 1000, 1000, 1000 ]

  component_stepsize_adapter_config:
    initial_stepsize: [0.0001, 0.0001, 0.0005, 0.0005]
    min_stepsize: [0.001, 0.001, 0.005, 0.005]
    max_stepsize: [0.1, 0.1, 0.5, 0.5]

grid:
  sample_selector_config:
      desired_samples_per_component: [750, 1500]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 0.1 ]

  model_initialization:
    num_initial_components: [ 1, 5, 20 ]

  gmmvi_runner_config:
      log_metrics_interval: [200]

  use_sample_database: [False]
  ng_estimator_config:
    only_use_own_samples: [True]
wandb:
    group: "samyrox_WINE"