---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
account: "project01800"
partition: "ignored"
job-name: "stkr"    # this will be the experiment's name in slurm

# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 3
time: 2-00:00:00

path_to_template: "clusterwork_slurm.sbatch"

---
name: "DEFAULT"

# Required: Can also be set in DEFAULT
path: "/work/scratch/j_arenz/exp3_hyperopt/sepyrux/"   # location to save results in
iterations: 100000
repetitions: 1 # number of times one set of parameters is run
reps_per_job: 1
reps_in_parallel: 1 # need to be 1 in order for wandb to work properly

algorithm_id: "SEPYRUX"

params:
    model_initialization:
        num_initial_components: 1

    sample_selector_config:
        desired_samples_per_component: 600
        ratio_reused_samples_to_desired: 1.61803

    component_stepsize_adapter_config:
        initial_stepsize: 0.00001
        min_stepsize: 0.00001
        max_stepsize: 0.1

    weight_stepsize_adapter_config:
        initial_stepsize: 1.

wandb:
    project: gmmvi-exp3

---
name: "BC"

experiment_id: "breast_cancer"

list:
  component_stepsize_adapter_config:
    initial_stepsize: [ 0.0005, 0.0005 ]
    min_stepsize: [ 0.001, 0.0001 ]
    max_stepsize: [ 0.05, 0.005 ]

grid:
  model_initialization:
    num_initial_components: [ 25, 50 ]

  sample_selector_config:
    desired_samples_per_component: [ 100, 200, 300 ]
    ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
    initial_stepsize: [ 0.001, 0.0001 ]

  max_database_size: [ 2000000 ]

  gmmvi_runner_config:
    log_metrics_interval: [ 150 ]
wandb:
    group: "sepyrux_bc"
---
name: "GC"

experiment_id: "german_credit"

list:
  component_stepsize_adapter_config:
    initial_stepsize: [ 0.0005, 0.0005 ]
    min_stepsize: [ 0.001, 0.0001 ]
    max_stepsize: [ 0.05, 0.005 ]

grid:
  model_initialization:
    num_initial_components: [ 25, 50 ]

  sample_selector_config:
    desired_samples_per_component: [ 100, 200, 300 ]
    ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
    initial_stepsize: [ 0.001, 0.0001 ]

  max_database_size: [ 2000000 ]

  gmmvi_runner_config:
    log_metrics_interval: [ 150 ]

wandb:
    group: "sepyrux_gc"
---
name: "BC_mb"

experiment_id: "breast_cancer_mb"

list:
  component_stepsize_adapter_config:
    initial_stepsize: [ 0.0005, 0.0005 ]
    min_stepsize: [ 0.001, 0.0001 ]
    max_stepsize: [ 0.05, 0.005 ]

grid:
  model_initialization:
    num_initial_components: [ 25, 50 ]

  sample_selector_config:
    desired_samples_per_component: [700, 900, 1100]
    ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
    initial_stepsize: [ 0.001, 0.0001 ]

  max_database_size: [ 2000000 ]

  gmmvi_runner_config:
    log_metrics_interval: [ 150 ]

wandb:
    group: "sepyrux_bcmb"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

list:
  component_stepsize_adapter_config:
    initial_stepsize: [ 0.0005, 0.0005 ]
    min_stepsize: [ 0.001, 0.0001 ]
    max_stepsize: [ 0.05, 0.005 ]

grid:
  model_initialization:
    num_initial_components: [ 25, 50 ]

  sample_selector_config:
    desired_samples_per_component: [700, 900, 1100]
    ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
    initial_stepsize: [ 0.001, 0.0001 ]

  max_database_size: [ 2000000 ]

  gmmvi_runner_config:
    log_metrics_interval: [ 250 ]
wandb:
    group: "sepyrux_gcmb"
---
name: "Planar4"

experiment_id: "planar_robot_4"

list:
  component_stepsize_adapter_config:
    initial_stepsize: [ 0.0005, 0.0005 ]
    min_stepsize: [ 0.001, 0.0001 ]
    max_stepsize: [ 0.05, 0.005 ]

grid:
  model_initialization:
    num_initial_components: [ 100, 300 ]

  sample_selector_config:
    desired_samples_per_component: [ 100, 200, 300 ]
    ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
    initial_stepsize: [ 0.001, 0.0001 ]

  gmmvi_runner_config:
    log_metrics_interval: [ 150 ]

  max_database_size: [ 2000000 ]
wandb:
    group: "sepyrux_planar_4"
---
name: "GMM20"

experiment_id: "gmm20"

list:
  component_stepsize_adapter_config:
      initial_stepsize: [0.0001, 0.0005]
      min_stepsize: [0.001, 0.005]
      max_stepsize: [0.1, 0.5]
grid:
  sample_selector_config:
      desired_samples_per_component: [100, 200, 300]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 1. ]

  model_initialization:
    num_initial_components: [10, 25, 50, 100]

wandb:
    group: "sepyrux_gmm20"
---
name: "GMM100"

experiment_id: "gmm100"

list:
  component_stepsize_adapter_config:
      initial_stepsize: [0.0001, 0.0005]
      min_stepsize: [0.001, 0.005]
      max_stepsize: [0.1, 0.5]
grid:
  sample_selector_config:
      desired_samples_per_component: [100, 200, 300]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 1. ]

  model_initialization:
    num_initial_components: [10, 25, 50, 100]

  max_database_size: [2000000]
wandb:
    group: "sepyrux_gmm100"
---
name: "STM20"

experiment_id: "stm20"

list:
  component_stepsize_adapter_config:
      initial_stepsize: [0.001, 0.01]
      min_stepsize: [0.005, 0.05]
      max_stepsize: [0.1, 0.1]
grid:
  sample_selector_config:
      desired_samples_per_component: [100, 200, 300]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 0.8, 0. ]

  ng_estimator_config:
    use_self_normalized_importance_weights: [True, False]

  model_initialization:
    num_initial_components: [25]

  max_database_size: [2000000]

  gmmvi_runner_config:
    log_metrics_interval: [ 150 ]
wandb:
    group: "sepyrux_stm20"