---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
account: "project01883"
partition: "ignored"
job-name: "stkr"    # this will be the experiment's name in slurm

# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 3
time: 2-00:00:00

path_to_template: "clusterwork_slurm.sbatch"

---
name: "DEFAULT"

# Required: Can also be set in DEFAULT
path: "/work/scratch/j_arenz/exp3_hyperopt/sepyrux/"   # location to save results in
iterations: 100000
repetitions: 1 # number of times one set of parameters is run
reps_per_job: 1
reps_in_parallel: 1 # need to be 1 in order for wandb to work properly

algorithm_id: "SEPYRUX"

params:
    model_initialization:
        num_initial_components: 1

    sample_selector_config:
        desired_samples_per_component: 600
        ratio_reused_samples_to_desired: 1.61803

    component_stepsize_adapter_config:
        initial_stepsize: 0.00001
        min_stepsize: 0.00001
        max_stepsize: 0.1

    weight_stepsize_adapter_config:
        initial_stepsize: 1.

wandb:
    project: gmmvi-exp3

---
name: "BC"

experiment_id: "breast_cancer"

grid:
    model_initialization:
        num_initial_components: [25, 50, 100, 150]

    sample_selector_config:
      desired_samples_per_component: [400, 600, 800]

    component_stepsize_adapter_config:
        min_stepsize: [0.0005, 0.00005]

wandb:
    group: "sepyrux_bc"
---
name: "GC"

experiment_id: "german_credit"

grid:
    model_initialization:
        num_initial_components: [50, 100, 150, 200]

    sample_selector_config:
      desired_samples_per_component: [600, 800, 1000]

    component_stepsize_adapter_config:
        min_stepsize: [0.001, 0.0001]

wandb:
    group: "sepyrux_gc"
---
name: "BC_mb"

experiment_id: "breast_cancer_mb"

grid:
    model_initialization:
        num_initial_components: [ 5, 20 ]

    sample_selector_config:
      desired_samples_per_component: [700, 900, 1100]
      ratio_reused_samples_to_desired: [1.61803]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.1, 0.85]

    component_stepsize_adapter_config:
      min_stepsize: [0.0001, 0.00001]

wandb:
    group: "sepyrux_bcmb"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

grid:
    model_initialization:
        num_initial_components: [ 5 ]

    sample_selector_config:
      desired_samples_per_component: [700, 900, 1200]
      ratio_reused_samples_to_desired: [0.]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.1, 0.85]

    component_stepsize_adapter_config:
      min_stepsize: [0.0001, 0.00005, 0.00001, 0.000005]

wandb:
    group: "sepyrux_gcmb"