num_componenter_adapter_type: "adaptive"
num_componenter_adapter_config:
  del_iters: TODO
  add_iters: TODO
  max_components: 1
  thresholds_for_add_heuristic: TODO
  min_weight_for_del_heuristic: TODO
  num_database_samples: TODO
  num_prior_samples: TODO
  prior_mean: TODO
  prior_scale: TODO
