---
name: "GC_mb"

experiment_id: "german_credit_mb"

list:
    num_component_adapter_config:
      del_iters: [200]
      add_iters: [250]

grid:
    sample_selector_config:
      desired_samples_per_component: [700, 900, 1200]
      ratio_reused_samples_to_desired: [0.]

    component_stepsize_adapter_config:
      initial_stepsize: [0.1, 0.01]

    weight_stepsize_adapter_config:
        initial_stepsize: [ 0.5, 0.1, 0.05, 0.01 ]
wandb:
    group: "samtron_gcmb"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

list:
    num_component_adapter_config:
      del_iters: [200]
      add_iters: [250]

grid:
    sample_selector_config:
      desired_samples_per_component: [700, 900, 1200]
      ratio_reused_samples_to_desired: [0.]

    component_stepsize_adapter_config:
      initial_stepsize: [0.1, 0.01]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.5, 0.05]
wandb:
    group: "samtron_gcmb"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

list:
    num_component_adapter_config:
      del_iters: [200]
      add_iters: [250]

grid:
    sample_selector_config:
      desired_samples_per_component: [700, 900, 1200]
      ratio_reused_samples_to_desired: [0.]

    component_stepsize_adapter_config:
      initial_stepsize: [0.1, 0.01]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.1, 0.01]
wandb:
    group: "samtron_gcmb"