---
name: "GC_mb"

experiment_id: "german_credit_mb"

grid:
    sample_selector_config:
      desired_samples_per_component: [700, 900, 1100]

    model_initialization:
        num_initial_components: [25, 50]

    component_stepsize_adapter_config:
        initial_stepsize: [0.001, 0.0001]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.001, 0.0001]

    max_database_size: [ 2000000 ]

    gmmvi_runner_config:
      log_metrics_interval: [ 150 ]

wandb:
    group: "sepyfux_gcmb"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

grid:
    model_initialization:
        num_initial_components: [ 5 ]

    sample_selector_config:
      desired_samples_per_component: [700, 900, 1200]
      ratio_reused_samples_to_desired: [0.]

    weight_stepsize_adapter_config:
        initial_stepsize: [ 0.05, 0.005 ]

    component_stepsize_adapter_config:
        initial_stepsize: [ 0.0001, 0.00005, 0.00001, 0.000005 ]

wandb:
    group: "sepyfux_gcmb"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

list:
    component_stepsize_adapter_config:
        initial_stepsize: [ 0.0001, 0.00005, 0.00001, 0.000005 ]
        min_stepsize: [ 0.001, 0.0005, 0.0001, 0.00005 ]
        max_stepsize: [ 0.1, 0.05, 0.01, 0.005 ]

grid:
    model_initialization:
        num_initial_components: [ 5 ]

    sample_selector_config:
      desired_samples_per_component: [700, 900, 1200]
      ratio_reused_samples_to_desired: [0.]

    weight_stepsize_adapter_config:
        initial_stepsize: [ 0.05, 0.005 ]

wandb:
    group: "sepyfux_gcmb"
---
name: "GC_mb"

experiment_id: "german_credit_mb"

grid:
    model_initialization:
        num_initial_components: [ 5 ]

    sample_selector_config:
      desired_samples_per_component: [700, 900, 1200]
      ratio_reused_samples_to_desired: [0.]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.1, 0.85]

    component_stepsize_adapter_config:
      initial_stepsize: [0.01, 0.005, 0.001, 0.0005]

wandb:
    group: "sepyfux_gcmb"