---
name: "GMM20"

experiment_id: "gmm20"

list:
  component_stepsize_adapter_config:
      initial_stepsize: [0.0001, 0.0005]
      min_stepsize: [0.001, 0.005]
      max_stepsize: [0.1, 0.5]
grid:
  sample_selector_config:
      desired_samples_per_component: [100, 200, 300]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 1. ]

  model_initialization:
    num_initial_components: [10, 25, 50, 100]

wandb:
    group: "sepyrux_gmm20"