---
name: "BC_mb"

experiment_id: "breast_cancer_mb"

list:
  component_stepsize_adapter_config:
    initial_stepsize: [ 0.0005, 0.0005 ]
    min_stepsize: [ 0.001, 0.0001 ]
    max_stepsize: [ 0.05, 0.005 ]

grid:
  model_initialization:
    num_initial_components: [ 25, 50 ]

  sample_selector_config:
    desired_samples_per_component: [700, 900, 1100]

  weight_stepsize_adapter_config:
    initial_stepsize: [ 0.001, 0.0001 ]

  max_database_size: [ 2000000 ]

  gmmvi_runner_config:
    log_metrics_interval: [ 150 ]

wandb:
    group: "sepyrux_bcmb"
---
name: "BC_mb"

experiment_id: "breast_cancer_mb"

grid:
    model_initialization:
        num_initial_components: [ 5, 20 ]

    sample_selector_config:
      desired_samples_per_component: [700, 900, 1100]
      ratio_reused_samples_to_desired: [1.61803]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.1, 0.85]

    component_stepsize_adapter_config:
      min_stepsize: [0.0001, 0.00001]

wandb:
    group: "sepyrux_bcmb"
---