---
name: "Planar4"

experiment_id: "planar_robot_4"

list:
    component_stepsize_adapter_config:
        initial_stepsize: [ 0.0001, 0.0005 ]
        min_stepsize: [ 0.001, 0.005 ]
        max_stepsize: [ 0.1, 0.1 ]

grid:
    sample_selector_config:
        desired_samples_per_component: [100, 150, 200]
        ratio_reused_samples_to_desired: [0.]

    weight_stepsize_adapter_config:
        initial_stepsize: [ 0.85 ]

    model_initialization:
      num_initial_components: [10, 100, 200, 300]
wandb:
    group: "sepyrux_planar_4"
---