---
name: "GMM100"

experiment_id: "gmm100"

list:
  num_component_adapter_config:
    del_iters: [ 25, 100 ]
    add_iters: [ 25, 30 ]

grid:
  sample_selector_config:
      desired_samples_per_component: [1500, 2500, 4000]
      ratio_reused_samples_to_desired: [0.]

  weight_stepsize_adapter_config:
      initial_stepsize: [ 1., 0.8 ]

  model_initialization:
    num_initial_components: [1, 5]

  max_database_size: [2000000]
wandb:
    group: "zamtrux_gmm100"