---
name: "GC_mb"

experiment_id: "german_credit_mb"

list:
    num_component_adapter_config:
      del_iters: [200]
      add_iters: [250]

grid:
    sample_selector_config:
      desired_samples_per_component: [3600, 4200, 5000]
      ratio_reused_samples_to_desired: [0., 1.61803]

    weight_stepsize_adapter_config:
        initial_stepsize: [0.1, 0.85]

    component_stepsize_adapter_config:
      initial_stepsize: [0.1, 0.001]

wandb:
    group: "zamtrux_gcmb"